### ISSUE TITLE
Fix .gitignore

### ISSUE THREAD

**Issue by umar14** [scottrpoulin/heroku-grafana-6.3.5#1]
Hey scott!

Nice fork! I tested it and had some issues but finally it worked. Thanks!
You need to modify your `.gitignore` file and exclude the `build` directory. Cloning this repo and pushing to Heroku would give erros since the `public/build` directory is excluded and not pushed.

Thanks
Umar

**Comment by scottrpoulin** [comment]
@umar14 Thanks for the heads up! I will get that fixed! I am glad it is working for you!

**Comment by umar14** [comment]
:+1: Thanks! Closing this
